version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - '${MYSQL_PORT}:3306'
    volumes:
      - ./db:/var/lib/mysql
